name: Test listing

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unit tests
        working-directory: scripts
        run: python3 -m unittest test_list_plugins.py -v
      - name: Refresh plugin list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 scripts/list_plugins.py
